### ISSUE TITLE
.pkl datasets

### ISSUE THREAD

**Issue by JoJoJun** [nickvdw/aspect-level-sentiment-classification#1]
Excuse me but, where can I get the *.pkl datasets? Or, can you tell me the format of these pkl files? How can I process the .zip files to get these .pkl files? Thanks

**Comment by nickvdw** [comment]
I added the pickle files for the aspect level part to this comment. These files are preprocessed version of the original dataset.

[pkl_files_aspect_level_sentiment_classification.zip](https://github.com/nickvdw/aspect-level-sentiment-classification/files/6099786/pkl_files_aspect_level_sentiment_classification.zip)
